package com.gcs.nlyte.web.persistance.dao.entity;
// Generated 20 Nov, 2017 6:23:45 PM by Hibernate Tools 5.2.5.Final

import java.util.Date;
/**
 * NltyeCustomerDataProcess generated by hbm2java
 */
public class NltyeCustomerDataProcess implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5391621555596301211L;
	private Integer processId;
	private NlyteCustomerDataTransStg nlyteCustomerDataTransStg;
	private NlyteMasterDataTransStg nlyteMasterDataTransStg;
	private Integer status;
	private Date createdDt;
	private Date updatedDt;
	private String perentage;

	public NltyeCustomerDataProcess() {
	}
	public NltyeCustomerDataProcess(NlyteCustomerDataTransStg nlyteCustomerDataTransStg,
			NlyteMasterDataTransStg nlyteMasterDataTransStg, Integer status, Date createdDt, Date updatedDt,String perentage) {
		this.nlyteCustomerDataTransStg = nlyteCustomerDataTransStg;
		this.nlyteMasterDataTransStg = nlyteMasterDataTransStg;
		this.status = status;
		this.createdDt = createdDt;
		this.updatedDt = updatedDt;
		this.perentage = perentage;
	}

	public Integer getProcessId() {
		return processId;
	}

	public void setProcessId(Integer processId) {
		this.processId = processId;
	}

	public NlyteCustomerDataTransStg getNlyteCustomerDataTransStg() {
		return nlyteCustomerDataTransStg;
	}

	public void setNlyteCustomerDataTransStg(NlyteCustomerDataTransStg nlyteCustomerDataTransStg) {
		this.nlyteCustomerDataTransStg = nlyteCustomerDataTransStg;
	}

	public NlyteMasterDataTransStg getNlyteMasterDataTransStg() {
		return nlyteMasterDataTransStg;
	}

	public void setNlyteMasterDataTransStg(NlyteMasterDataTransStg nlyteMasterDataTransStg) {
		this.nlyteMasterDataTransStg = nlyteMasterDataTransStg;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Date getCreatedDt() {
		return createdDt;
	}

	public void setCreatedDt(Date createdDt) {
		this.createdDt = createdDt;
	}

	public Date getUpdatedDt() {
		return updatedDt;
	}

	public void setUpdatedDt(Date updatedDt) {
		this.updatedDt = updatedDt;
	}
	public String getPerentage() {
		return perentage;
	}
	public void setPerentage(String perentage) {
		this.perentage = perentage;
	}
	
	
	}
