package com.gcs.nlyte.web.persistance.dao.entity;
// Generated 28 Oct, 2017 6:23:45 PM by Hibernate Tools 5.2.5.Final

import java.util.Date;
import java.util.List;

/**
 * NlyteCustomerDataTransStg generated by hbm2java
 */
public class NlyteCustomerDataTransStg implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5372392455260177951L;
	private Integer nctId;
	private NlyteCustomerDataStg nlyteCustomerDataStg;
	private String modelTx;
	private String manufacturerTx;
	private String materialTypTx;
	private String materialSubTypTx;
	private Float widthNm;
	private Float depthNm;
	private Float heightNm;
	private Float weightNm;
	private String copperPortsTx;
	private String fiberPortsTx;
	private String undefPortsTx;
	private Float powerConsmptNm;
	private Date createdDt;
	private Date updatedDt;
	private boolean validYn;
	private Integer nmsId;
	private String nmsValue;
	private boolean activeYn;
	private String matchPercentage;
	//private Integer cmsId;

	public NlyteCustomerDataTransStg() {
	}

	public NlyteCustomerDataTransStg(NlyteCustomerDataStg nlyteCustomerDataStg, Date createdDt, Date updatedDt,
			boolean validYn, boolean activeYn) {
		this.nlyteCustomerDataStg = nlyteCustomerDataStg;
		this.createdDt = createdDt;
		this.updatedDt = updatedDt;
		this.validYn = validYn;
		this.activeYn = activeYn;
	}

	public NlyteCustomerDataTransStg(NlyteCustomerDataStg nlyteCustomerDataStg, String modelTx, String manufacturerTx,
			String materialTypTx, String materialSubTypTx, Float widthNm, Float depthNm, Float heightNm,
			Float weightNm, String copperPortsTx, String fiberPortsTx, String undefPortsTx, Float powerConsmptNm,
			Date createdDt, Date updatedDt, boolean validYn, Integer nmsId, String nmsValue, boolean activeYn,String matchPercentage) {
		this.nlyteCustomerDataStg = nlyteCustomerDataStg;
		this.modelTx = modelTx;
		this.manufacturerTx = manufacturerTx;
		this.materialTypTx = materialTypTx;
		this.materialSubTypTx = materialSubTypTx;
		this.widthNm = widthNm;
		this.depthNm = depthNm;
		this.heightNm = heightNm;
		this.weightNm = weightNm;
		this.copperPortsTx = copperPortsTx;
		this.fiberPortsTx = fiberPortsTx;
		this.undefPortsTx = undefPortsTx;
		this.powerConsmptNm = powerConsmptNm;
		this.createdDt = createdDt;
		this.updatedDt = updatedDt;
		this.validYn = validYn;
		this.nmsId = nmsId;
		this.nmsValue = nmsValue;
		this.activeYn = activeYn;
		this.matchPercentage = matchPercentage;
		//this.cmsId = cmsId;
	}

	public Integer getNctId() {
		return this.nctId;
	}

	public void setNctId(Integer nctId) {
		this.nctId = nctId;
	}

	public NlyteCustomerDataStg getNlyteCustomerDataStg() {
		return this.nlyteCustomerDataStg;
	}

	public void setNlyteCustomerDataStg(NlyteCustomerDataStg nlyteCustomerDataStg) {
		this.nlyteCustomerDataStg = nlyteCustomerDataStg;
	}

	public String getModelTx() {
		return this.modelTx;
	}

	public void setModelTx(String modelTx) {
		this.modelTx = modelTx;
	}

	public String getManufacturerTx() {
		return this.manufacturerTx;
	}

	public void setManufacturerTx(String manufacturerTx) {
		this.manufacturerTx = manufacturerTx;
	}

	public String getMaterialTypTx() {
		return this.materialTypTx;
	}

	public void setMaterialTypTx(String materialTypTx) {
		this.materialTypTx = materialTypTx;
	}

	public String getMaterialSubTypTx() {
		return this.materialSubTypTx;
	}

	public void setMaterialSubTypTx(String materialSubTypTx) {
		this.materialSubTypTx = materialSubTypTx;
	}

	public Float getWidthNm() {
		return this.widthNm;
	}

	public void setWidthNm(Float widthNm) {
		this.widthNm = widthNm;
	}

	public Float getDepthNm() {
		return this.depthNm;
	}

	public void setDepthNm(Float depthNm) {
		this.depthNm = depthNm;
	}

	public Float getHeightNm() {
		return this.heightNm;
	}

	public void setHeightNm(Float heightNm) {
		this.heightNm = heightNm;
	}

	public Float getWeightNm() {
		return this.weightNm;
	}

	public void setWeightNm(Float weightNm) {
		this.weightNm = weightNm;
	}

	public String getCopperPortsTx() {
		return this.copperPortsTx;
	}

	public void setCopperPortsTx(String copperPortsTx) {
		this.copperPortsTx = copperPortsTx;
	}

	public String getFiberPortsTx() {
		return this.fiberPortsTx;
	}

	public void setFiberPortsTx(String fiberPortsTx) {
		this.fiberPortsTx = fiberPortsTx;
	}

	public String getUndefPortsTx() {
		return this.undefPortsTx;
	}

	public void setUndefPortsTx(String undefPortsTx) {
		this.undefPortsTx = undefPortsTx;
	}

	public Float getPowerConsmptNm() {
		return this.powerConsmptNm;
	}

	public void setPowerConsmptNm(Float powerConsmptNm) {
		this.powerConsmptNm = powerConsmptNm;
	}

	public Date getCreatedDt() {
		return this.createdDt;
	}

	public void setCreatedDt(Date createdDt) {
		this.createdDt = createdDt;
	}

	public Date getUpdatedDt() {
		return this.updatedDt;
	}

	public void setUpdatedDt(Date updatedDt) {
		this.updatedDt = updatedDt;
	}

	public boolean isValidYn() {
		return this.validYn;
	}

	public void setValidYn(boolean validYn) {
		this.validYn = validYn;
	}

	public Integer getNmsId() {
		return this.nmsId;
	}

	public void setNmsId(Integer nmsId) {
		this.nmsId = nmsId;
	}

	public String getNmsValue() {
		return this.nmsValue;
	}

	public void setNmsValue(String nmsValue) {
		this.nmsValue = nmsValue;
	}

	public boolean isActiveYn() {
		return this.activeYn;
	}

	public void setActiveYn(boolean activeYn) {
		this.activeYn = activeYn;
	}

	public String getMatchPercentage() {
		return matchPercentage;
	}

	public void setMatchPercentage(String matchPercentage) {
		this.matchPercentage = matchPercentage;
	}
	
	/*public Integer getCmsId() {
		return cmsId;
	}

	public void setCmsId(Integer cmsId) {
		this.cmsId = cmsId;
	}*/

	/*@Override
	public String toString() {
		return "NlyteCustomerDataTransStg [nctId=" + nctId + ", nlyteCustomerDataStg=" + nlyteCustomerDataStg
				+ ", modelTx=" + modelTx + ", manufacturerTx=" + manufacturerTx + ", materialTypTx=" + materialTypTx
				+ ", materialSubTypTx=" + materialSubTypTx + ", widthNm=" + widthNm + ", depthNm=" + depthNm
				+ ", heightNm=" + heightNm + ", weightNm=" + weightNm + ", copperPortsTx=" + copperPortsTx
				+ ", fiberPortsTx=" + fiberPortsTx + ", undefPortsTx=" + undefPortsTx + ", powerConsmptNm="
				+ powerConsmptNm + ", createdDt=" + createdDt + ", updatedDt=" + updatedDt + ", validYn=" + validYn
				+ ", nmsId=" + nmsId + ", nmsValue=" + nmsValue + ", activeYn=" + activeYn + "]";
	}*/



	
}
