package com.gcs.nlyte.web.persistance.dao.entity;
// Generated 28 Oct, 2017 6:23:45 PM by Hibernate Tools 5.2.5.Final

import java.util.Date;

/**
 * NlyteMasterDataTransStg generated by hbm2java
 */
public class NlyteMasterDataTransStg implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5391621555596301210L;
	private Integer nmtId;
	private NlyteMasterDataStg nlyteMasterDataStg;
	private Integer materialNm;
	private String materialNmTx;
	private String modelTx;
	private String manufacturerTx;
	private String materialTypTx;
	private String materialSubTypTx;
	private Float widthNm;
	private Float depthNm;
	private Float heightNm;
	private Float weightNm;
	private String copperPortsTx;
	private String fiberPortsTx;
	private String undefPortsTx;
	private Float powerConsmptNm;
	private Date createdDt;
	private Date updatedDt;
	private boolean activeYn;

	public NlyteMasterDataTransStg() {
	}

	public NlyteMasterDataTransStg(NlyteMasterDataStg nlyteMasterDataStg, Date createdDt, Date updatedDt,
			boolean activeYn) {
		this.nlyteMasterDataStg = nlyteMasterDataStg;
		this.createdDt = createdDt;
		this.updatedDt = updatedDt;
		this.activeYn = activeYn;
	}

	public NlyteMasterDataTransStg(NlyteMasterDataStg nlyteMasterDataStg, Integer materialNm, String materialNmTx,
			String modelTx, String manufacturerTx, String materialTypTx, String materialSubTypTx, Float widthNm,
			Float depthNm, Float heightNm, Float weightNm, String copperPortsTx, String fiberPortsTx,
			String undefPortsTx, Float powerConsmptNm, Date createdDt, Date updatedDt, boolean activeYn) {
		this.nlyteMasterDataStg = nlyteMasterDataStg;
		this.materialNm = materialNm;
		this.materialNmTx = materialNmTx;
		this.modelTx = modelTx;
		this.manufacturerTx = manufacturerTx;
		this.materialTypTx = materialTypTx;
		this.materialSubTypTx = materialSubTypTx;
		this.widthNm = widthNm;
		this.depthNm = depthNm;
		this.heightNm = heightNm;
		this.weightNm = weightNm;
		this.copperPortsTx = copperPortsTx;
		this.fiberPortsTx = fiberPortsTx;
		this.undefPortsTx = undefPortsTx;
		this.powerConsmptNm = powerConsmptNm;
		this.createdDt = createdDt;
		this.updatedDt = updatedDt;
		this.activeYn = activeYn;
	}

	public Integer getNmtId() {
		return this.nmtId;
	}

	public void setNmtId(Integer nmtId) {
		this.nmtId = nmtId;
	}

	public NlyteMasterDataStg getNlyteMasterDataStg() {
		return this.nlyteMasterDataStg;
	}

	public void setNlyteMasterDataStg(NlyteMasterDataStg nlyteMasterDataStg) {
		this.nlyteMasterDataStg = nlyteMasterDataStg;
	}

	public Integer getMaterialNm() {
		return this.materialNm;
	}

	public void setMaterialNm(Integer materialNm) {
		this.materialNm = materialNm;
	}

	public String getMaterialNmTx() {
		return this.materialNmTx;
	}

	public void setMaterialNmTx(String materialNmTx) {
		this.materialNmTx = materialNmTx;
	}

	public String getModelTx() {
		return this.modelTx;
	}

	public void setModelTx(String modelTx) {
		this.modelTx = modelTx;
	}

	public String getManufacturerTx() {
		return this.manufacturerTx;
	}

	public void setManufacturerTx(String manufacturerTx) {
		this.manufacturerTx = manufacturerTx;
	}

	public String getMaterialTypTx() {
		return this.materialTypTx;
	}

	public void setMaterialTypTx(String materialTypTx) {
		this.materialTypTx = materialTypTx;
	}

	public String getMaterialSubTypTx() {
		return this.materialSubTypTx;
	}

	public void setMaterialSubTypTx(String materialSubTypTx) {
		this.materialSubTypTx = materialSubTypTx;
	}

	public Float getWidthNm() {
		return this.widthNm;
	}

	public void setWidthNm(Float widthNm) {
		this.widthNm = widthNm;
	}

	public Float getDepthNm() {
		return this.depthNm;
	}

	public void setDepthNm(Float depthNm) {
		this.depthNm = depthNm;
	}

	public Float getHeightNm() {
		return this.heightNm;
	}

	public void setHeightNm(Float heightNm) {
		this.heightNm = heightNm;
	}

	public Float getWeightNm() {
		return this.weightNm;
	}

	public void setWeightNm(Float weightNm) {
		this.weightNm = weightNm;
	}

	public String getCopperPortsTx() {
		return this.copperPortsTx;
	}

	public void setCopperPortsTx(String copperPortsTx) {
		this.copperPortsTx = copperPortsTx;
	}

	public String getFiberPortsTx() {
		return this.fiberPortsTx;
	}

	public void setFiberPortsTx(String fiberPortsTx) {
		this.fiberPortsTx = fiberPortsTx;
	}

	public String getUndefPortsTx() {
		return this.undefPortsTx;
	}

	public void setUndefPortsTx(String undefPortsTx) {
		this.undefPortsTx = undefPortsTx;
	}

	public Float getPowerConsmptNm() {
		return this.powerConsmptNm;
	}

	public void setPowerConsmptNm(Float powerConsmptNm) {
		this.powerConsmptNm = powerConsmptNm;
	}

	public Date getCreatedDt() {
		return this.createdDt;
	}

	public void setCreatedDt(Date createdDt) {
		this.createdDt = createdDt;
	}

	public Date getUpdatedDt() {
		return this.updatedDt;
	}

	public void setUpdatedDt(Date updatedDt) {
		this.updatedDt = updatedDt;
	}

	public boolean isActiveYn() {
		return this.activeYn;
	}

	public void setActiveYn(boolean activeYn) {
		this.activeYn = activeYn;
	}

}
