package com.gcs.nlyte.web.persistance.dao.entity;
// Generated 28 Oct, 2017 6:23:45 PM by Hibernate Tools 5.2.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NlyteCustomerDataStg generated by hbm2java
 */
public class NlyteCustomerDataStg implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -7117345685351855236L;
	private Integer cmsId;
	private String descriptionTx;
	private Date lstUpdtDtm;
	private Date createdDt;
	private byte[] excelFileBlb;
	private boolean activeYn;
	private String userDisplayNameTx;
	private String loginId;
	private String status;
	private String processStatus;
	private String excelFileName;
	private String uniqueId;
	
	private long matchCount;
	private long unMatchCount;
	private long multiMatchedCount;
	
	public long getMatchCount() {
		return matchCount;
	}
	public void setMatchCount(long matchCount) {
		this.matchCount = matchCount;
	}
	public long getUnMatchCount() {
		return unMatchCount;
	}
	public void setUnMatchCount(long unMatchCount) {
		this.unMatchCount = unMatchCount;
	}
	public long getMultiMatchedCount() {
		return multiMatchedCount;
	}
	public void setMultiMatchedCount(long multiMatchedCount) {
		this.multiMatchedCount = multiMatchedCount;
	}
	
	

	/**
	 * @return the excelFileName
	 */
	public String getExcelFileName() {
		return excelFileName;
	}

	public String getProcessStatus() {
		return processStatus;
	}

	public void setProcessStatus(String processStatus) {
		this.processStatus = processStatus;
	}

	/**
	 * @param excelFileName the excelFileName to set
	 */
	public void setExcelFileName(String excelFileName) {
		this.excelFileName = excelFileName;
	}

	/**
	 * @return the uniqueId
	 */
	public String getUniqueId() {
		return uniqueId;
	}

	/**
	 * @param uniqueId the uniqueId to set
	 */
	public void setUniqueId(String uniqueId) {
		this.uniqueId = uniqueId;
	}

	private Set<NlyteCustomerDataTransStg> nlyteCustomerDataTransStgs = new HashSet<NlyteCustomerDataTransStg>(0);
	
	public String getUserDisplayNameTx() {
		return userDisplayNameTx;
	}

	public void setUserDisplayNameTx(String userDisplayNameTx) {
		this.userDisplayNameTx = userDisplayNameTx;
	}

	public String getLoginId() {
		return loginId;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	

	public NlyteCustomerDataStg() {
	}

	public NlyteCustomerDataStg(Date lstUpdtDtm, Date createdDt, boolean activeYn) {
		this.lstUpdtDtm = lstUpdtDtm;
		this.createdDt = createdDt;
		this.activeYn = activeYn;
	}

	public NlyteCustomerDataStg(String descriptionTx, Date lstUpdtDtm, Date createdDt, byte[] excelFileBlb,
			boolean activeYn,String loginId,String status,String userDisplayNameTx, String uniqueId, String excelFileName,Set<NlyteCustomerDataTransStg> nlyteCustomerDataTransStgs) {
		this.descriptionTx = descriptionTx;
		this.lstUpdtDtm = lstUpdtDtm;
		this.createdDt = createdDt;
		this.excelFileBlb = excelFileBlb;
		this.activeYn = activeYn;
		this.loginId=loginId;
		this.status=status;
		this.uniqueId=uniqueId;
		this.excelFileName=excelFileName;
		this.userDisplayNameTx=userDisplayNameTx;
		this.nlyteCustomerDataTransStgs = nlyteCustomerDataTransStgs;
	}

	public Integer getCmsId() {
		return this.cmsId;
	}

	public void setCmsId(Integer cmsId) {
		this.cmsId = cmsId;
	}

	public String getDescriptionTx() {
		return this.descriptionTx;
	}

	public void setDescriptionTx(String descriptionTx) {
		this.descriptionTx = descriptionTx;
	}

	public Date getLstUpdtDtm() {
		return this.lstUpdtDtm;
	}

	public void setLstUpdtDtm(Date lstUpdtDtm) {
		this.lstUpdtDtm = lstUpdtDtm;
	}

	public Date getCreatedDt() {
		return this.createdDt;
	}

	public void setCreatedDt(Date createdDt) {
		this.createdDt = createdDt;
	}

	public byte[] getExcelFileBlb() {
		return this.excelFileBlb;
	}

	public void setExcelFileBlb(byte[] excelFileBlb) {
		this.excelFileBlb = excelFileBlb;
	}

	public boolean isActiveYn() {
		return this.activeYn;
	}

	public void setActiveYn(boolean activeYn) {
		this.activeYn = activeYn;
	}

	public Set<NlyteCustomerDataTransStg> getNlyteCustomerDataTransStgs() {
		return this.nlyteCustomerDataTransStgs;
	}

	public void setNlyteCustomerDataTransStgs(Set<NlyteCustomerDataTransStg> nlyteCustomerDataTransStgs) {
		this.nlyteCustomerDataTransStgs = nlyteCustomerDataTransStgs;
	}

	public String toString(){
		return nlyteCustomerDataTransStgs.toString();
		//return NlyteCustomerDataStg(this.descriptionTx, this.lstUpdtDtm, this.createdDt, this.excelFileBlb,
			//	this.activeYn,this.loginId,this.status,this.userDisplayNameTx,this.nlyteCustomerDataTransStgs);
	}

}
