package com.gcs.nlyte.web.persistance.dao.entity;
// Generated 28 Oct, 2017 6:23:45 PM by Hibernate Tools 5.2.5.Final

import java.util.Arrays;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NlyteMasterDataStg generated by hbm2java
 */
public class NlyteMasterDataStg implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8137254350931872727L;
	private Integer nmsId;
	private String descriptionTx;
	private Date lstUpdtDtm;
	private Date createdDt;
	private byte[] excelFileBlb;
	private boolean activeYn;
	private String userDisplayNameTx;
	private String loginId;
	private String status;
	private String uniqueId;
	private String excelFileName;
	
	/**
	 * @return the uniqueId
	 */
	public String getUniqueId() {
		return uniqueId;
	}

	/**
	 * @param uniqueId the uniqueId to set
	 */
	public void setUniqueId(String uniqueId) {
		this.uniqueId = uniqueId;
	}

	/**
	 * @return the excelFileName
	 */
	public String getExcelFileName() {
		return excelFileName;
	}

	/**
	 * @param excelFileName the excelFileName to set
	 */
	public void setExcelFileName(String excelFileName) {
		this.excelFileName = excelFileName;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getUserDisplayNameTx() {
		return userDisplayNameTx;
	}

	public void setUserDisplayNameTx(String userDisplayNameTx) {
		this.userDisplayNameTx = userDisplayNameTx;
	}

	public String getLoginId() {
		return loginId;
	}

	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	private Set<NlyteMasterDataTransStg> nlyteMasterDataTransStgs = new HashSet<NlyteMasterDataTransStg>(0);

	public NlyteMasterDataStg() {
	}

	public NlyteMasterDataStg(Date lstUpdtDtm, Date createdDt, boolean activeYn) {
		this.lstUpdtDtm = lstUpdtDtm;
		this.createdDt = createdDt;
		this.activeYn = activeYn;
	}

	public NlyteMasterDataStg(String descriptionTx, Date lstUpdtDtm, Date createdDt, byte[] excelFileBlb,
			boolean activeYn,String loginId,String status,String userDisplayNameTx, String uniqueId, String excelFileName, Set<NlyteMasterDataTransStg> nlyteMasterDataTransStgs) {
		this.descriptionTx = descriptionTx;
		this.lstUpdtDtm = lstUpdtDtm;
		this.createdDt = createdDt;
		this.excelFileBlb = excelFileBlb;
		this.activeYn = activeYn;
		this.loginId=loginId;
		this.status=status;
		this.userDisplayNameTx=userDisplayNameTx;
		this.excelFileName=excelFileName;
		this.uniqueId=uniqueId;
		this.nlyteMasterDataTransStgs = nlyteMasterDataTransStgs;
	}

	public Integer getNmsId() {
		return this.nmsId;
	}

	public void setNmsId(Integer nmsId) {
		this.nmsId = nmsId;
	}

	public String getDescriptionTx() {
		return this.descriptionTx;
	}

	public void setDescriptionTx(String descriptionTx) {
		this.descriptionTx = descriptionTx;
	}

	public Date getLstUpdtDtm() {
		return this.lstUpdtDtm;
	}

	public void setLstUpdtDtm(Date lstUpdtDtm) {
		this.lstUpdtDtm = lstUpdtDtm;
	}

	public Date getCreatedDt() {
		return this.createdDt;
	}

	public void setCreatedDt(Date createdDt) {
		this.createdDt = createdDt;
	}

	public byte[] getExcelFileBlb() {
		return this.excelFileBlb;
	}

	public void setExcelFileBlb(byte[] excelFileBlb) {
		this.excelFileBlb = excelFileBlb;
	}

	public boolean isActiveYn() {
		return this.activeYn;
	}

	public void setActiveYn(boolean activeYn) {
		this.activeYn = activeYn;
	}

	public Set<NlyteMasterDataTransStg> getNlyteMasterDataTransStgs() {
		return this.nlyteMasterDataTransStgs;
	}

	public void setNlyteMasterDataTransStgs(Set<NlyteMasterDataTransStg> nlyteMasterDataTransStgs) {
		this.nlyteMasterDataTransStgs = nlyteMasterDataTransStgs;
	}

	@Override
	public String toString() {
		return "NlyteMasterDataStg [nmsId=" + nmsId + ", descriptionTx=" + descriptionTx + ", lstUpdtDtm=" + lstUpdtDtm
				+ ", createdDt=" + createdDt + ", excelFileBlb=" + Arrays.toString(excelFileBlb) + ", activeYn="
				+ activeYn + ", userDisplayNameTx=" + userDisplayNameTx + ", loginId=" + loginId + ", status=" + status
				+ ", uniqueId=" + uniqueId + ", excelFileName=" + excelFileName + ", nlyteMasterDataTransStgs="
				+ nlyteMasterDataTransStgs + "]";
	}

	/*public String toString() {
		return nlyteMasterDataTransStgs.toString();
	}*/
}
